datacite/mastino

- stage/services/metrics-api/_sashimi.auto.tfvars
- stage/services/metrics-api/input.tf
- stage/services/metrics-api/main.tf
- stage/services/metrics-api/metrics-api.json
- stage/services/metrics-api/terraform.tf
- stage/services/metrics-api/var.tf
@richardhallett #pairdevops #pairprogramming
> Moving sashimi to mastino

- stage/services/metrics-api/input.tf
- stage/services/metrics-api/metrics-api.json
- stage/services/metrics-api/var.tf
> to remove hardcoded configurations

- prod-us-east/services/bastion/input.tf
- prod-us-east/services/bastion/main.tf
- prod-us-east/services/bastion/terraform.tf
- prod-us-east/services/bastion/user_data.cfg
- prod-us-east/services/bastion/var.tf
Initial PR to move bastion over.
> Add US Bastion host

- prod-eu-west/services/metrics-api/metrics-api.json
I put development first after looking at other repos but I think it should be production.
> environment change

- stage/services/ors/task-definitions/wsgi.json
- stage/services/ors/var.tf
ORS v1.1 with task queue, core metadata compliant
> ORS new version

- stage/services/handle/handle.json
- stage/services/handle/input.tf
- stage/services/handle/main.tf
- stage/services/handle/var.tf
This PR is the terraform config changes to create a new handle server instance in fargate, this will replace the LB rules that point to the old handle server running on the main MDS test service.
> Docker version of the test handle server

- stage/services/ors/indexd.tf
- stage/services/ors/task-definitions/indexd.json
- stage/services/ors/task-definitions/wsgi.json
- stage/services/ors/var.tf
I added the indexd service, which requires the new env variables
- indexd_url (uses default)
- indexd_username
- indexd_password
The username and password can be set to anything
> Added indexd service

- stage/services/ors/_worker.auto.tfvars
- stage/services/ors/var.tf
Allows worker to be updated along with uWSGI
> Added map to worker variables

- stage/services/ors/input.tf
- stage/services/ors/task-definitions/wsgi.json
(XML parsing as last resort, and Template Fixes)
> ors-stage: updating to container version 1.23 

- stage/services/ors/task-definitions/wsgi.json
removed globus auth in test environment
> ors-stage: updated wsgi container to v1.24

- stage/services/ors/task-definitions/wsgi.json
(produces real doi's; authentication enabled for DOI minting)
> ors-stage: Updated wsgi container 

- prod-eu-west/services/schema/main.tf
- prod-eu-west/services/schema/routing-rules.json
Creates new routing rules for the schema site.
> updates routing rules for schema site

- prod-eu-west/services/search/main.tf
updated minimum number of containers to 4
> minimum number of containers to 4

- test/services/cheetoh/main.tf
- test/services/client-api/main.tf
- test/services/doi/main.tf
- test/services/mds/main.tf
Reduce the number of containers in the test system to 1 per service.
> reduce desired_count to 1

- stage/data-storage/elasticsearch/input.tf
- stage/data-storage/elasticsearch/main.tf
Enable Cognito to access Kibana
Enable Cognito access to Elastic Search
> enabling cognito in es

- stage/data-storage/elasticsearch/main.tf
> Configuring es-cog-kibana

- stage/data-storage/elasticsearch/main.tf
Commented out cognito options to create the identity pool first to see whether I can fix the cycle error.
> disable cognito

- stage/services/message-queue/main.tf
- test/services/message-queue/input.tf
- test/services/message-queue/main.tf
- test/services/message-queue/sqs.json
- test/services/message-queue/terraform.tf
- test/services/message-queue/var.tf
Problem is using the same message queue for stage and test, as both are in the `stage` environment.
Add new message queues for test. Use different queue prefix, based on `ES_PREFIX` ENV variable.
> add message queues for test

- global/dns/main.tf
- global/dns/var.tf
Setup dkim record for salesforce
Added as a aws_route53_record. Value is passed in using terraform variable.
I haven't added the alternative record yet.
> setup dkim salesforce

- global/dns/main.tf
- global/dns/var.tf
Create alternate dkim for saleforce
Added this as another resource
> add alt dkim salesforce

- pidnotebooks/stage/input.tf
- pidnotebooks/stage/main.tf
- pidnotebooks/stage/s3_cloudfront.json
- pidnotebooks/stage/terraform.tf
- pidnotebooks/stage/var.tf
> add pidnotebooks

- test/services/metrics-api/_sashimi.auto.tfvars
- test/services/metrics-api/input.tf
- test/services/metrics-api/main.tf
- test/services/metrics-api/metrics-api.json
- test/services/metrics-api/terraform.tf
- test/services/metrics-api/var.tf
Sets up Metrics api for sandbox
closes: https://github.com/datacite/mastino/issues/92
copy paste old api
> Sets up Metrics api for sandbox

- prod-eu-west/services/raw-resolution-logs/input.tf
- prod-eu-west/services/raw-resolution-logs/main.tf
- prod-eu-west/services/raw-resolution-logs/terraform.tf
- prod-eu-west/services/raw-resolution-logs/var.tf
Adds an S3 bucket for resolution logs
addresses: https://github.com/datacite/datacite/issues/1104
Using S3 bucket to store raw logs
> S3 bucket for resolution logs

- prod-eu-west/services/metrics-api/input.tf
- prod-eu-west/services/metrics-api/main.tf
- prod-eu-west/services/metrics-api/terraform.tf
- prod-eu-west/services/metrics-api/var.tf
- stage/services/metrics-api/input.tf
- stage/services/metrics-api/main.tf
- stage/services/metrics-api/terraform.tf
- stage/services/metrics-api/var.tf
- test/services/metrics-api/input.tf
- test/services/metrics-api/main.tf
- test/services/metrics-api/terraform.tf
- test/services/metrics-api/var.tf
Related to datacite/sashimi#133.  Adding buckets to store reports.
> Metrics API bucket.

- prod-eu-west/services/metrics-api/input.tf
- prod-eu-west/services/metrics-api/main.tf
- prod-eu-west/services/metrics-api/terraform.tf
- prod-eu-west/services/metrics-api/var.tf
- stage/services/metrics-api/input.tf
- stage/services/metrics-api/main.tf
- stage/services/metrics-api/terraform.tf
- stage/services/metrics-api/var.tf
- test/services/metrics-api/input.tf
- test/services/metrics-api/main.tf
- test/services/metrics-api/terraform.tf
- test/services/metrics-api/var.tf
> Revert "Metrics API bucket."

- prod-eu-west/services/metrics-api/main.tf
- prod-eu-west/services/metrics-api/var.tf
- stage/services/metrics-api/main.tf
- stage/services/metrics-api/var.tf
- test/services/metrics-api/main.tf
- test/services/metrics-api/var.tf
Adding a bucket for test/stage/prod metrics-api.
> Adding a bucket for metrics-api.

- prod-eu-west/services/metrics-api/input.tf
- prod-eu-west/services/metrics-api/main.tf
- prod-eu-west/services/metrics-api/s3_public_read.json
- stage/services/metrics-api/input.tf
- stage/services/metrics-api/main.tf
- stage/services/metrics-api/s3_public_read.json
- test/services/metrics-api/input.tf
- test/services/metrics-api/main.tf
- test/services/metrics-api/s3_public_read.json
Fix policy errors with recently created buckets.
> Metrics-api buckets. (corrected policy).

- stage/services/metrics-api/main.tf
Adds backup to reports files in s3 storage.
Uses the version, lifecycle, and expiration features of the AWS S3 bucket to keep old versions of modified/deleted files, and to save costs by transitioning them to lower cost storage after given amounts of time.  Expiration is set to delete older versions after 365 days.
Only added settings to stage for testing.  Once this has been confirmed to do no harm to what we have, settings can be moved to production, as well.
[Should You Back Up an Ultra-Redundant Object Storage Service?](https://www.groupwaretech.com/ultra-redundant-object-storage-service-absolutely/#:~:text=AWS%20themselves%20say%3A%20%E2%80%9CAmazon%20S3,failures%2C%20errors%20and%20threats.%E2%80%9D)
[Managing Your Amazon S3 …
> Issue datacite/sashimi#133 - Add file backup for reports stored in S3.

- stage/services/blog/input.tf
> another attempt to update aws provider version for blog stage

- stage/services/blog/main.tf
A record isn't working well on the Siteground side for staging. Trying CNAME instead.
> try cname instead of a record

- stage/services/blog/var.tf
Add missing variable declaration
> add domain name var

- stage/services/blog/main.tf
> try a record again

- prod-eu-west/services/blog/main.tf
- prod-eu-west/services/blog/var.tf
- stage/services/blog/var.tf
Finalize blog migration by pointing blog.datacite.org to Siteground Wordpress site.
> DNS record changes to point blog.datacite.org to siteground WP

- prod-eu-west/services/blog/input.tf
> update TF aws provider version on blog prod

- prod-eu-west/services/blog/main.tf
> update cf origin id name

- prod-eu-west/services/content-negotiation/main.tf
Increase resources available to Content Negotiation task, and temporarily disable the container restarts under high load
> Update CN container config

- prod-eu-west/services/metrics-api/_sashimi.auto.tfvars.tmpl
- stage/services/metrics-api/_sashimi.auto.tfvars.tmpl
- test/services/metrics-api/_sashimi.auto.tfvars.tmpl
closes: none
Add template files to address sashimi issue #148 - adding github workflows to replace Travis CI.
> Issue #148 - add workflow for sashimi.

- prod-eu-west/services/metrics-api/metrics-api.json
- stage/services/metrics-api/metrics-api.json
- test/services/metrics-api/metrics-api.json
Related to: Sashimi [issue#148](https://github.com/datacite/sashimi/issues/148) - need to pull images from github, not dockerhub.
> Re: Issue #148 - need to pull from github instead of dockerhub.

- prod-eu-west/services/salesforce-api/main.tf
Increase the timeout allowance on the 'update_salesforce_daily' lambda.  It is timing out regularly because it needs that much time to finish its processing.
> Increase timeout on update_salesforce_daily lambda.

- prod-eu-west/services/re3data/_schnauzer.auto.tfvars.tmpl
- stage/services/re3data/_schnauzer.auto.tfvars.tmpl
Add templates for updating the Schnauzer terraform variables from github actions
> Schnauzer autodeploy

- .github/workflows/tfsec.yml
enables static analysis tool to detect potential security risks.
`tfsec`, a static analysis tool that scans Terraform templates to find potential security issues.
> add tfsec on PR

- .github/workflows/terraform.yml
- global/dns/main.tf
- global/dns/var.tf
- prod-eu-west/services/design/input.tf
- prod-eu-west/services/design/main.tf
- prod-eu-west/services/design/s3_cloudfront.json
- prod-eu-west/services/design/terraform.tf
- prod-eu-west/services/design/var.tf
This is preparation for when the design system gets published. We are planning to use the path for either be the entry point of the toolkit or be the domain of a zeroHeight (TBD) or a similar type of tool.
> Design system path

- prod-eu-west/services/design/main.tf
The object was stored using a form of Server Side Encryption. The correct parameters must be provided to retrieve the object.
> remove due to error in deployment

- stage/services/search/main.tf
Adds missing slash for path attribute in redirect. 
> Added missing / for search path redirect

- prod-eu-west/services/profiles/var.tf
- stage/services/profiles/var.tf
closes: none
Modify the default value of cdn_url where appropriate. (vars.tf - volpino/profiles is the only place).
> Update cdn_url to pull assets from assets.datacite.org

- prod-eu-west/services/assets/input.tf
- stage/services/assets/input.tf
- stage/services/assets/main.tf
- stage/services/assets/terraform.tf
- test/services/assets/input.tf
- test/services/assets/main.tf
- test/services/assets/terraform.tf
closes: [mastino#1837](https://github.com/datacite/datacite/issues/1837)
Do speculative runs in Terraform to see what any differences are between the mastino specification and what is actually in AWS.  There were no differences.  
Then update the Terraform version as much as possible as quickly as possible.  I updated to just before v13 because it required mostly just syntactic changes.
Finally, make sure the correct version of the AWS provider was explicitly specified. 
- Offer suggestions on how to improve code e.g. simplification or expanding …
> Update mastino to reflect current assets.datacite.org AWS resources

- prod-eu-west/services/mds/input.tf
- prod-eu-west/services/mds/mds.json
- stage/services/mds/main.tf
- stage/services/mds/mds.json
- test/services/mds/main.tf
- test/services/mds/mds.json
Mods to mds.json in each environment to use version and sha appropriately.
> MDS fixes.

- prod-eu-west/services/bastion/var.tf
> Upgrade to latest AMI

- prod-eu-west/services/bastion/main.tf
> Try specifying the IP address manually

- stage/services/datafiles/_tesem.auto.tfvars
- stage/services/datafiles/_tesem.auto.tfvars.tmpl
- stage/services/datafiles/datafiles.json
- stage/services/datafiles/input.tf
- stage/services/datafiles/main.tf
- stage/services/datafiles/terraform.tf
- stage/services/datafiles/var.tf
Add setup for the data files prototype service
> add initial datafiles staging setup

- prod-eu-west/services/datafiles/_tesem.auto.tfvars
- prod-eu-west/services/datafiles/_tesem.auto.tfvars.tmpl
- prod-eu-west/services/datafiles/datafiles.json
- prod-eu-west/services/datafiles/input.tf
- prod-eu-west/services/datafiles/main.tf
- prod-eu-west/services/datafiles/terraform.tf
- prod-eu-west/services/datafiles/var.tf
> add first pass datafiles production code

- prod-eu-west/services/client-api/queue-worker.tf
> bump staging queue worker desired count

- test/services/federation/_vaestgoetaspets.auto.tfvars
- test/services/federation/_vaestgoetaspets.auto.tfvars.tmpl
- test/services/federation/federation.json
- test/services/federation/input.tf
- test/services/federation/main.tf
- test/services/federation/terraform.tf
- test/services/federation/var.tf
GraphQL doesn't exist in the Test environment, preventing people from developing integrations against it using test data (e.g RAiDs)
closes: https://github.com/datacite/datacite/issues/2134
Adds confirguration for the apollo federation server in test environment
> Initial setup for test federation server

- prod-eu-west/services/client-api/queue-worker.tf
- stage/services/client-api/queue-worker.tf
> change staging desired count and revert change to prod

- stage/services/client-api/queue-worker.tf
> change staging queue worker desired_count to 1

- global/dns/main.tf
Add DNS record for corpus.stage.datacite.org
> Add A record for corpus.stage domain

- global/dns/main.tf
> point corpus.stage to ALB instead of EC2 instance

- global/dns/main.tf
Add CNAME record for SSL cert validation
> add cname record for ssl cert validation

- modules/datacite_queues/main.tf
Create the events queue
closes: https://github.com/datacite/datacite/issues/2238
> create events queue

- modules/datacite_queues/main.tf
closes: https://github.com/datacite/product-backlog/issues/185
> remove old event queue

- stage/services/events/.terraform.lock.hcl
- stage/services/events/_events.auto.tfvars
- stage/services/events/_events.auto.tfvars.tmpl
- stage/services/events/events.json
- stage/services/events/input.tf
- stage/services/events/main.tf
- stage/services/events/terraform.tf
- stage/services/events/var.tf
closes: https://github.com/datacite/datacite/issues/2306
> Add events staging configuration

- stage/services/events/main.tf
> rework events env vars

- stage/services/events/var.tf
> remove api aws vars

- stage/services/events/main.tf
> add aws vars for events stage

- stage/services/events/main.tf
> change the failture threshold for events in staging

- modules/datacite_queues/main.tf
closes: https://github.com/datacite/datacite/issues/2351
> Add events_index sqs queue

- prod-eu-west/services/events/.terraform.lock.hcl
- prod-eu-west/services/events/_events.auto.tfvars
- prod-eu-west/services/events/_events.auto.tfvars.tmpl
- prod-eu-west/services/events/events.json
- prod-eu-west/services/events/input.tf
- prod-eu-west/services/events/main.tf
- prod-eu-west/services/events/terraform.tf
- prod-eu-west/services/events/var.tf
closes: https://github.com/datacite/datacite/issues/2387
> Events production configuration

- prod-eu-west/services/events/events.json
> Remove elastic_password variable

- prod-eu-west/services/events/main.tf
> Fix heartbeat interval

- prod-eu-west/services/events/main.tf
> Change events prod lb priority

- prod-eu-west/services/events/main.tf
> Remove evetns interval and timeout settings for healthcheck

- prod-eu-west/services/events/main.tf
> Add healthcheck interval and timeout for events prod

- modules/datacite_queues/out.tf
- prod-eu-west/services/events/main.tf
> Remove mis-configuration

- prod-eu-west/services/events/main.tf
> Bump the event service desired count from one to two

- stage/services/profiles/input.tf
- stage/services/profiles/profiles.json
- stage/services/profiles/var.tf
Add new environment variables for ORCID Search & Link and Auto-update in profiles staging
> Add new variables for ORCID Search & Link and Auto-update

- stage/services/client-api/main.tf
Just adds a new general purpose S3 bucket for where metadata will be stored.
Note this is for metadata history PR, so not all metadata.
N/A
N/A
> stage/client-api - Add storage bucket for metadata

- stage/vpc/waf.tf
Add tiered rate limit 
closes: https://github.com/datacite/product-backlog/issues/374
Add 3 rules to handle the tiered rate limit
> Tiered rate limit - staging

- stage/vpc/waf.tf
closes: https://github.com/datacite/product-backlog/issues/374
> Enable sample requests

- stage/vpc/waf.tf
> fix custom message key reference

- prod-eu-west/vpc/waf.tf
closes: https://github.com/datacite/product-backlog/issues/374
> Add tiered rate limit to prod WAF

- stage/services/metadata-completeness-api/var.tf
> fix var name

- stage/services/metadata-completeness-api/main.tf
> fix conflicting priority

- prod-eu-west/services/client-api/member.tf
Bump the container definition for member-api to match the client-api setup
> Bump member-api task resources to match client-api config
