datacite/mastino

- prod-eu-west/services/levriero/main.tf
to avoid conflicts, we will queue the rest of the changes
> disable eventdata agent while we reindex events

- stage/data-storage/elasticsearch/elasticsearch_policy.json
This PR is for removing the requirements to do AWS request signing on ES requests.
For now only our TEST infrastructure.
Reason is to allow us to proxy via SSH locally through our bastion server (curie), this will then let us use existing tools e.g. kibana for accessing the raw ES index, this would help with debugging and development.
Note, I'm not sure the Principle set to * before was actually doing anything, the docs suggest that while a wildcard is allowed, you have to specify either accounts or IAM.
> Remove signing for ES requests within the VPC

- test/services/client-api/client-api.json
- test/services/client-api/main.tf
- test/services/client-api/var.tf
Use `ES_PREFIX` in test system, so that we can have multiple indexes for `client-api` in the same Elasticsearch cluster.
> use es-prefix in test system

- stage/services/client-api/client-api.json
- stage/services/client-api/main.tf
- stage/services/client-api/var.tf
This allows more than one `client-api` service in one elasticsearch cluster.
> use es-prefix for stage environment

- test/services/cheetoh/cheetoh.json
- test/services/client-api/client-api.json
- test/services/client-api/main.tf
- test/services/doi/doi.json
- test/services/mds/main.tf
- test/services/mds/mds.json
Use version-tagged containers for the production infrastructure, so that test is always in sync with production.
> Use production containers

- stage/data-storage/elasticsearch/main.tf
The Elasticsearch Cluster on stage has run out of disk space.
Increase volume_size from 60 to 80 GB.
> Increase volume size for Elasticsearch Stage

- stage/data-storage/elasticsearch/main.tf
We are running low on disk space despite the increase from 60 to 80 GB last week. Will now increase to 120 GB.
> increase volume size es stage

- prod-eu-west/services/client-api/client-api.json
Detailed logging to understand the usage of Client API 
Client API log level changed from 'warn' to 'info'. However, we need to keep an eye on the log numbers and improve the quality of the logging
> ClientAPI log level change

- prod-eu-west/data-storage/elasticsearch/main.tf
Moves to seperate cloudwatch log group.
So it's easier to filter out specifically slow search queries, as there is too much log noise.
Additionally will be easier to send just these to datadog if desired.
new cloudwatch log group.
> Seperate elasticsearch slow search logs

- global/dns/main.tf
Resolve deliverability issues for emails sent from Salesforce. A member reported that invoices sent from Salesforce are flagged as spam by their email system due to SPF validation failure. 
Add _spf.salesforce.com to DNS record for datacite.org as described in https://help.salesforce.com/articleView?id=emailadmin_spf_include_salesforce.htm
> add salesforce spf entry to txt record for datacite.org

- stage/services/blog/main.tf
- stage/services/blog/var.tf
Point blog.stage.datacite.org to Siteground Wordpress staging site and point new subdomain oldblog.stage.datacite.org to current Middleman blog, in preparation for blog migration.
Notes:
- Not putting blog.stage.datacite.org on Cloudfront at this point. To be done after everything is confirmed working.
- After deploying, Wordpress site URL needs to be updated in Siteground.
- Add A record  to point blog.stage.datacite.org to Siteground per docs https://www.siteground.com/kb/point-website-domain-siteground (I don't know what they suggest A record instead of CNAME, but they do)
- Add CNAME records that point oldblog.stage.datacite.org to S3 bucket
- Update Cloudfront distribution origin and alias (origin ID doesn't _need_ to be updated, just doing so to avoid confusion)
- Be humble in the …
> point blog.stage to WP staging site and point oldblog.stage to current blog

- stage/services/blog/input.tf
Terraform run fails for stage blog service due to outdated aws provider
> update aws provider version for blog stage

- prod-eu-west/services/crossref-agent/main.tf
- prod-eu-west/services/crossref-related-agent/main.tf
aws doesn't support nodejs10 anymore
closes: [_Add github issue that originated this PR_](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/crossref-agent?tab=code)
similar to previous update  https://github.com/datacite/mastino/commit/92e3aaee5c917be1ddfe07867071f06db5ab8bc8
> update nodejs for AWS support

- stage/services/repository-finder/input.tf
- stage/services/repository-finder/main.tf
- stage/services/repository-finder/var.tf
- stage/services/search/main.tf
Adds Search and Repository Finder redirects to Commons in stage to test implementation of redirects for production services. 
Changes Repository Finder Route53 records to target the load balancer and adds a load balancer listener rule to redirect repositoryfinder.stage.datacite.org requests to stage Commons. Adjusts Search load balancer listener rule to redirect to stage Commons. 
> Adds Search and Repository Finder redirects to Commons in stage

- prod-eu-west/services/crossref-orcid-agent/main.tf
- prod-eu-west/services/crossref-related-agent/main.tf
The crossref-related-agent and crossref-orcid-agent lamdbas are not intended to run and haven't in some time. This PR disables both for now by setting a cron expression that never runs. 
closes: datacite/datacite#1831
> Disables crossref-related and crossref-orcid crons

- prod-eu-west/services/repository-finder/input.tf
- prod-eu-west/services/repository-finder/main.tf
- prod-eu-west/services/repository-finder/var.tf
- prod-eu-west/services/search/main.tf
Adds Search and Repository Finder redirects to Commons. **Only to be merged after 1 June 2023**, when these services retire.
closes: datacite/datacite#1820
Changes Repository Finder Route53 records to target the load balancer and adds a load balancer listener rule to redirect repositoryfinder.datacite.org requests to Commons. Adjusts Search load balancer listener rule to redirect to Commons. 
> Adds production redirects to Commons for Search and Repository Finder

- stage/services/homepage/input.tf
- stage/services/homepage/main.tf
- stage/services/homepage/var.tf
In preparation for migrating the homepage site (datacite.org) from Middleman hosted on S3 to Wordpress hosted on Siteground, the Siteground staging site needs a domain. 
Added A record to point new subdomain homepage.stage.datacite.org to Siteground staging site IP address.
- [ X] New feature (non-breaking change which adds functionality)
> add dns record for homepage.stage.datacite.org

- prod-eu-west/services/homepage/main.tf
Siteground supports a "staging copy" feature, which generates a temp copy of a live site for development purposes. A new subdomain is automatically created for each temp copy, formatted like staging2.datacite.org, but it does not have any DNS records unless the parent domain is managed by Siteground.
Add DNS A record for staging2.datacite.org that points to Siteground
> DNS for Siteground staging copy

- prod-eu-west/services/homepage/main.tf
Siteground allows creating unlimited staging copies of the Wordpress homepage site, each with domains like stagingX.datacite.org where the number in the domain is incremented by 1 for each subsequent staging copy. Staging need DNS records pointing to our Siteground IP in order to make them reachable.
Pre-emptively create DNS records for staging3.datacite.org through staging10.datacite.org, so that they are reachable on creation by the engagement team.
- Ensure you give …
> add dns for staging copies 3-10

- prod-eu-west/services/client-api/queue-worker.tf
This uses metric_queries to aggregate lupo and lupo_background queues and then base the alarm on this.
Period is 2 minutes with an evaluation period of once every 2 minutes for scaling up and once every 4 minutes for scaling down.
Improve queue scaling 
closes: datacite/datacite#2070
Allows watching over the two most important queues.
> Use combined metrics for alarm thresholds

- global/dns/main.tf
Point corpus.stage.datacite.org to ALB instead of directly to EC2 instance
> point corpus.stage to ALB instead of EC2 instance

- global/dns/main.tf
Corpus prod DNS updates: add CNAME record for SSL validation, point corpus.datacite.org to load balancer instead of IP
> add ssl validation for corpus prod and point corpus.datacite.org to LB

- prod-eu-west/services/client-api/queue-worker.tf
Add the new doi_registration queue to the autoscaling alarm config, to ensure that worker scaling happens for all lupo queues.
> Add doi_registration queue to queue worker alarm config

- prod-eu-west/services/client-api/client-api.json
- prod-eu-west/services/client-api/queue-worker.json
- stage/services/client-api/client-api.json
- stage/services/client-api/queue-worker.json
- test/services/client-api/queue-worker.json
This PR removes environment variables that are no longer used by the client-api service and its queue worker.
The environment variables `PLUGIN_MANIFEST_URL` and `PLUGIN_OPENAPI_URL` were identified as unused in the current codebase for the client-api service. This change removes these variables from the service configurations across the `prod-eu-west`, `stage`, and `test` environments to clean up the configuration files.
- Removed the `PLUGIN_MANIFEST_URL` environment variable from:
- `prod-eu-west/services/client-api/client-api.json`
- `prod-eu-west/services/client-api/queue-worker.json`
- `stage/services/client-api/client-api.json`
- `stage/services/client-api/queue-worker.json`
- `test/services/client-api/queue-worker.json`
- Removed the `PLUGIN_OPENAPI_URL` environment variable from …
> Remove unused plugin env vars from test and prod config

- modules/datacite_queues/main.tf
This PR introduces a new SQS queue, `lupo_queue_batches_other_doi`, and its corresponding dead-letter queue, `queue_batches_other_doi-dead-letter`. This new queue is intended to handle the batch processing of DOIs that are not DataCite DOIs.
This change addresses the need for a dedicated queue to manage batch operations for "other" DOIs by provisioning the required SQS resources in the `datacite_queues` module.
*   **Added `lupo_queue_batches_other_doi` SQS Queue:** A new AWS SQS queue is created with a `redrive_policy` pointing to its dedicated dead-letter queue and a `visibility_timeout_seconds` of 300.
*   **Added `queue_batches_other_doi-dead-letter` SQS Queue:** A new AWS SQS queue is created to serve as the dead-letter queue for `lupo_queue_batches_other_doi`.
*   **Prevent Destroy …
> Add OtherDoi batch enqueue queue

- prod-eu-west/services/client-api/queue-worker.json
- prod-eu-west/services/client-api/queue-worker.tf
- prod-eu-west/services/client-api/var.tf
- test/services/client-api/queue-worker.json
- test/services/client-api/queue-worker.tf
- test/services/client-api/var.tf
This PR introduces a new configurable environment variable, `SHORYUKEN_CONCURRENCY`, to manage the concurrency level of the Shoryuken queue worker. This allows for dynamic adjustment of how many jobs Shoryuken processes simultaneously, which can be crucial for performance tuning and resource management.
The changes enable the `SHORYUKEN_CONCURRENCY` and `CONCURRENCY` environment variables to be set for the `queue-worker` service in both `prod-eu-west` and `test` environments. This is achieved by introducing a new Terraform variable `shoryuken_concurrency` with a default value of "30". This variable is then passed as an environment variable to the ECS task definition.
- **Added `SHORYUKEN_CONCURRENCY` and `CONCURRENCY` environment variables**: These are added to the `containerDefinitions` …
> Shoryuken concurrency configuration to queue workers in prod and test
